# Generated by Django 3.1.2 on 2020-10-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('risk', models.CharField(max_length=10)),
                ('abstract', models.CharField(max_length=300)),
                ('impact', models.CharField(max_length=400)),
                ('ease_of_exploitation', models.CharField(max_length=10)),
                ('owasp_category', models.CharField(max_length=100)),
                ('cvss', models.FloatField()),
                ('cwe', models.IntegerField()),
                ('recommendation', models.TextField()),
                ('poc', models.ImageField(upload_to='uploads/')),
                ('date', models.DateField(auto_now_add=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.domain')),
            ],
        ),
    ]
