# Generated by Django 3.1.2 on 2020-10-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='quarter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bug',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.domain'),
        ),
    ]
