# Generated by Django 3.1.2 on 2020-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='host_ip',
            field=models.CharField(default='127.0.0.1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='port',
            field=models.CharField(default='443', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='reference',
            field=models.TextField(default='https://www.acunetix.com'),
            preserve_default=False,
        ),
    ]
